-- MADE 전체 테이블 조회
SELECT
    ATCOL.OWNER AS "사용자 계정"
    , ATCOL.TABLE_NAME AS "테이블명"
    , ATCOM.COMMENTS AS "테이블 설명"
    , ATCOL.COLUMN_NAME AS "컬럼명"
    , ATCOL.DATA_TYPE AS "데이터 타입"
    , ATCOL.DATA_LENGTH AS "데이터 크기"
    , ATCOL.NULLABLE AS "NN"
    , ATCOL.DATA_DEFAULT AS "기본값"
    , ACCOM.COMMENTS AS "컬럼 설명"
FROM ALL_TAB_COLUMNS ATCOL
    LEFT JOIN ALL_TAB_COMMENTS ATCOM
    ON ATCOL.TABLE_NAME = ATCOM.TABLE_NAME
    LEFT JOIN ALL_COL_COMMENTS ACCOM
    ON ATCOM.TABLE_NAME = ACCOM.TABLE_NAME AND ATCOL.COLUMN_NAME = ACCOM.COLUMN_NAME
WHERE ATCOL.OWNER = 'KMS'
ORDER BY ATCOL.TABLE_NAME ASC, ATCOL.COLUMN_ID
;

-- MADE 전체 제약조건 조회
SELECT
    TABLE_NAME AS "테이블명"
    , CONSTRAINT_NAME AS "제약조건명"
    , CASE WHEN CONSTRAINT_TYPE = 'P' THEN '기본키'
        WHEN CONSTRAINT_TYPE = 'U' THEN '고유키'
        WHEN CONSTRAINT_TYPE = 'R' THEN '외래키'
        ELSE NULL
        END AS "제약조건 키"
    , R_CONSTRAINT_NAME AS "참조 제약조건명"
    , DELETE_RULE AS "작업여부"
FROM ALL_CONSTRAINTS
WHERE OWNER = 'KMS'
AND CONSTRAINT_TYPE IN ('P', 'U', 'R')
AND SUBSTR(CONSTRAINT_NAME, 1, 4) != 'BIN$'
ORDER BY TABLE_NAME ASC
;

-- 공통코드 테이블 삭제.
DROP TABLE COMCDVAL;
-- 팔로우 테이블 삭제.
DROP TABLE FOLLOW;
-- 댓글-답글 테이블 삭제.
DROP TABLE CMTANSWER;
-- 댓글 테이블 삭제.
DROP TABLE COMMENTS;
-- 메인 게시글_좋아요 테이블 삭제.
DROP TABLE FEEDLIKE;
-- 메인 게시글 이미지 테이블 삭제.
DROP TABLE FEEDIMAGE;
-- 메인 게시글 테이블 삭제.
DROP TABLE FEED;
-- 블랙리스트 테이블 삭제.
DROP TABLE BLACKLIST;
-- 신고 테이블 삭제.
DROP TABLE REPORT;
-- 신고-답변 테이블 삭제.
DROP TABLE RPANSWER;
-- 1:1문의-답변 테이블 삭제.
DROP TABLE CPANSWER;
-- 1:1문의 테이블 삭제.
DROP TABLE COMPLAIN;
-- 일반회원 테이블 삭제.
DROP TABLE BASICMEMBER;

-- 공통코드 테이블 생성.
CREATE TABLE COMCDVAL
(
	COMCDVAL_NO   VARCHAR2(30)  NOT NULL -- <!-- 공통코드 번호 -->
	, CD          VARCHAR2(20)           -- <!-- 테이블 분류 코드 -->
	, TABLE_NAME  VARCHAR2(100) NOT NULL -- <!-- 테이블명 -->
	, COLUMN_NAME VARCHAR2(100) NOT NULL -- <!-- 컬럼명(영문) -->
	, VAL         VARCHAR2(100)          -- <!-- 컬럼명(국문) -->
	, CONSTRAINT COMCDVAL_PK PRIMARY KEY (COMCDVAL_NO)
);
COMMENT ON TABLE COMCDVAL IS '공통코드 테이블';
COMMENT ON COLUMN COMCDVAL.COMCDVAL_NO IS '공통코드 번호, 형식:CCV+0001';
COMMENT ON COLUMN COMCDVAL.TABLE_NAME IS '테이블명';
COMMENT ON COLUMN COMCDVAL.CD IS '테이블 분류 코드';
COMMENT ON COLUMN COMCDVAL.COLUMN_NAME IS '컬럼명(영문)';
COMMENT ON COLUMN COMCDVAL.VAL IS '컬럼명(국문)';

-- 일반회원 테이블 생성.
CREATE TABLE BASICMEMBER
(
	BM_NO           VARCHAR2(30)  NOT NULL                 -- <!-- 일반회원 번호 -->
	, BM_ID         VARCHAR2(40)  NOT NULL                 -- <!-- 일반회원 아이디 -->
	, BM_PW         VARCHAR2(40)  NOT NULL                 -- <!-- 일반회원 비밀번호 -->
	, BM_IMG        VARCHAR2(4000)                         -- <!-- 일반회원 프로필사진 -->
	, BM_NICK       VARCHAR2(60)  NOT NULL                 -- <!-- 일반회원 닉네임 -->
	, BM_NAME       VARCHAR2(60)  NOT NULL                 -- <!-- 일반회원 이름 -->
	, BM_PHONE      VARCHAR2(20)                           -- <!-- 일반회원 휴대폰 -->
	, BM_EMAIL      VARCHAR2(100) NOT NULL                 -- <!-- 일반회원 이메일 -->
	, BM_AUTH       VARCHAR2(1)   DEFAULT '0'     NOT NULL -- <!-- 일반회원 권한 -->
	, BM_DELETEYN   VARCHAR2(2)   DEFAULT 'Y'     NOT NULL -- <!-- 일반회원 삭제여부 -->
	, BM_INSERTDATE DATE          DEFAULT SYSDATE NOT NULL -- <!-- 일반회원 가입일 -->
	, BM_UPDATEDATE DATE          DEFAULT SYSDATE NOT NULL -- <!-- 일반회원 수정일 -->
	, BM_DELETEDATE DATE                                   -- <!-- 일반회원 삭제일 -->
	, CONSTRAINT BASICMEMBER_PK PRIMARY KEY (BM_NO)
	, CONSTRAINT BASICMEMBER_UK1 UNIQUE (BM_ID)
);
COMMENT ON TABLE BASICMEMBER IS '일반회원 테이블';
COMMENT ON COLUMN BASICMEMBER.BM_NO IS '일반회원 번호, 형식:BM+YYYYMMDD+0001';
COMMENT ON COLUMN BASICMEMBER.BM_ID IS '일반회원 아이디';
COMMENT ON COLUMN BASICMEMBER.BM_PW IS '일반회원 비밀번호';
COMMENT ON COLUMN BASICMEMBER.BM_IMG IS '일반회원 프로필사진';
COMMENT ON COLUMN BASICMEMBER.BM_NICK IS '일반회원 닉네임';
COMMENT ON COLUMN BASICMEMBER.BM_NAME IS '일반회원 이름';
COMMENT ON COLUMN BASICMEMBER.BM_PHONE IS '일반회원 휴대폰';
COMMENT ON COLUMN BASICMEMBER.BM_EMAIL IS '일반회원 이메일';
COMMENT ON COLUMN BASICMEMBER.BM_AUTH IS '일반회원 권한';
COMMENT ON COLUMN BASICMEMBER.BM_DELETEYN IS '일반회원 삭제여부';
COMMENT ON COLUMN BASICMEMBER.BM_INSERTDATE IS '일반회원 가입일';
COMMENT ON COLUMN BASICMEMBER.BM_UPDATEDATE IS '일반회원 수정일';
COMMENT ON COLUMN BASICMEMBER.BM_DELETEDATE IS '일반회원 삭제일';

-- 팔로우 테이블 생성.
CREATE TABLE FOLLOW
(
	FOLLOW_NO   VARCHAR2(30) NOT NULL -- <!-- 팔로우 번호 -->
	, BM_NO     VARCHAR2(30) NOT NULL -- <!-- 일반회원 번호(본인) -->
	, REG_BM_NO VARCHAR2(30) NOT NULL -- <!-- 일반회원 번호(상대) -->
	, CONSTRAINT FOLLOW_PK PRIMARY KEY (FOLLOW_NO)
	, CONSTRAINT FOLLOW_FK1 FOREIGN KEY (BM_NO) REFERENCES BASICMEMBER (BM_NO)
	, CONSTRAINT FOLLOW_FK2 FOREIGN KEY (REG_BM_NO) REFERENCES BASICMEMBER (BM_NO)
);
COMMENT ON TABLE FOLLOW IS '팔로우 테이블';
COMMENT ON COLUMN FOLLOW.FOLLOW_NO IS '팔로우 번호, 형식:F+YYYYMMDD+0001';
COMMENT ON COLUMN FOLLOW.BM_NO IS '일반회원 번호(본인)';
COMMENT ON COLUMN FOLLOW.REG_BM_NO IS '일반회원 번호(상대)';

-- 메인 게시글 테이블 생성.
CREATE TABLE FEED
(
	FEED_NO           VARCHAR2(30)   NOT NULL              -- <!-- 메인 게시글 번호 -->
	, BM_NO           VARCHAR2(30)   NOT NULL              -- <!-- 일반회원 번호(작성자) -->
	, FEED_TYPE_CD    VARCHAR2(20)                         -- <!-- 메인 게시글 메뉴 구분 코드 -->
	, FEED_TITLE      VARCHAR2(100)  NOT NULL              -- <!-- 메인 게시글 제목 -->
	, FEED_CONTENT    VARCHAR2(4000)                       -- <!-- 메인 게시글 내용 -->
	, FEED_DELETEYN   VARCHAR2(2) DEFAULT 'Y'     NOT NULL -- <!-- 메인 게시글 삭제여부 -->
	, FEED_INSERTDATE DATE        DEFAULT SYSDATE NOT NULL -- <!-- 메인 게시글 등록일 -->
	, FEED_UPDATEDATE DATE        DEFAULT SYSDATE NOT NULL -- <!-- 메인 게시글 수정일 -->
	, FEED_DELETEDATE DATE                                 -- <!-- 메인 게시글 삭제일 -->
	, CONSTRAINT FEED_PK PRIMARY KEY (FEED_NO)
	, CONSTRAINT FEED_FK1 FOREIGN KEY (BM_NO) REFERENCES BASICMEMBER (BM_NO)
);
COMMENT ON TABLE FEED IS '메인 게시글 테이블';
COMMENT ON COLUMN FEED.FEED_NO IS '메인 게시글 번호, 형식:FEED+YYYYMMDD+0001';
COMMENT ON COLUMN FEED.BM_NO IS '일반회원 번호(작성자)';
COMMENT ON COLUMN FEED.FEED_TYPE_CD IS '메인 게시글 메뉴 구분 코드, 형식:MCAT+0001';
COMMENT ON COLUMN FEED.FEED_TITLE IS '메인 게시글 제목';
COMMENT ON COLUMN FEED.FEED_CONTENT IS '메인 게시글 내용';
COMMENT ON COLUMN FEED.FEED_DELETEYN IS '메인 게시글 삭제여부';
COMMENT ON COLUMN FEED.FEED_INSERTDATE IS '메인 게시글 등록일';
COMMENT ON COLUMN FEED.FEED_UPDATEDATE IS '메인 게시글 수정일';
COMMENT ON COLUMN FEED.FEED_DELETEDATE IS '메인 게시글 삭제일';

-- 메인 게시글 좋아요 테이블 생성.
CREATE TABLE FEEDLIKE
(
	FL_NO VARCHAR2(30) NOT NULL       -- <!-- 좋아요 번호 -->
	, FEED_NO   VARCHAR2(30) NOT NULL -- <!-- 메인 게시글 번호 -->
	, BM_NO     VARCHAR2(30) NOT NULL -- <!-- 일반회원 번호 -->
	, CONSTRAINT FEEDLIKE_PK PRIMARY KEY (FL_NO)
	, CONSTRAINT FEEDLIKE_FK1 FOREIGN KEY (FEED_NO) REFERENCES FEED (FEED_NO)
	, CONSTRAINT FEEDLIKE_FK2 FOREIGN KEY (BM_NO) REFERENCES BASICMEMBER (BM_NO)
);
COMMENT ON TABLE FEEDLIKE IS '메인 게시글 좋아요 테이블';
COMMENT ON COLUMN FEEDLIKE.FL_NO IS '좋아요 번호, 형식:FL+YYYYMMDD+0001';
COMMENT ON COLUMN FEEDLIKE.FEED_NO IS '메인 게시글 번호';
COMMENT ON COLUMN FEEDLIKE.BM_NO IS '일반회원 번호';

-- 메인 게시글 이미지 테이블 생성.
CREATE TABLE FEEDIMAGE
(
	FI_NO     VARCHAR2(30)  NOT NULL -- <!-- 메인 게시글 이미지 번호 -->
	, FI_PATH VARCHAR2(500) DEFAULT 'https://made-s3.s3.ap-northeast-2.amazonaws.com/mainimage/' NOT NULL -- <!-- 메인 게시글 이미지 파일경로 -->
	, FI_FILE VARCHAR2(1000)  NOT NULL -- <!-- 메인 게시글 이미지 파일명 -->
	, FEED_NO VARCHAR2(30)  NOT NULL -- <!-- 메인 게시글 번호 -->
	, CONSTRAINT FEEDIMAGE_PK PRIMARY KEY (FI_NO)
);
COMMENT ON TABLE FEEDIMAGE IS '메인 게시글_좋아요 테이블';
COMMENT ON COLUMN FEEDIMAGE.FI_NO IS '메인 게시글 이미지 번호, 형식:FI+YYYMMDD+0001';
COMMENT ON COLUMN FEEDIMAGE.FI_PATH IS '메인 게시글 이미지 파일경로';
COMMENT ON COLUMN FEEDIMAGE.FI_FILE IS '메인 게시글 이미지 파일명';
COMMENT ON COLUMN FEEDIMAGE.FEED_NO IS '메인 게시글 번호';

-- 댓글 테이블 생성.
CREATE TABLE COMMENTS
(
	CMT_NO           VARCHAR2(30)   NOT NULL              -- <!-- 댓글 번호 -->
	, FEED_NO        VARCHAR2(30)   NOT NULL              -- <!-- 메인 게시글 번호 -->
	, BM_NO          VARCHAR2(30)   NOT NULL              -- <!-- 일반회원 번호(작성자) -->
	, CMT_CONTENT    VARCHAR2(4000) NOT NULL              -- <!-- 댓글 내용 -->
	, CMT_DELETEYN   VARCHAR2(2) DEFAULT 'Y' NOT NULL     -- <!-- 댓글 삭제여부 -->
	, CMT_INSERTDATE DATE        DEFAULT SYSDATE NOT NULL -- <!-- 댓글 등록일 -->
	, CMT_UPDATEDATE DATE        DEFAULT SYSDATE NOT NULL -- <!-- 댓글 수정일 -->
	, CMT_DELETEDATE DATE                                 -- <!-- 댓글 삭제일 -->
	, CONSTRAINT COMMENTS_PK PRIMARY KEY (CMT_NO)
	, CONSTRAINT COMMENTS_FK1 FOREIGN KEY (FEED_NO) REFERENCES FEED (FEED_NO)
	, CONSTRAINT COMMENTS_FK2 FOREIGN KEY (BM_NO) REFERENCES BASICMEMBER (BM_NO)
);
COMMENT ON TABLE COMMENTS IS '댓글 테이블';
COMMENT ON COLUMN COMMENTS.CMT_NO IS '댓글 번호, 형식:CMT+YYYYMMDD+0001';
COMMENT ON COLUMN COMMENTS.FEED_NO IS '메인 게시글 번호';
COMMENT ON COLUMN COMMENTS.BM_NO IS '일반회원 번호(작성자)';
COMMENT ON COLUMN COMMENTS.CMT_CONTENT IS '댓글 내용';
COMMENT ON COLUMN COMMENTS.CMT_DELETEYN IS '댓글 삭제여부';
COMMENT ON COLUMN COMMENTS.CMT_INSERTDATE IS '댓글 등록일';
COMMENT ON COLUMN COMMENTS.CMT_UPDATEDATE IS '댓글 수정일';
COMMENT ON COLUMN COMMENTS.CMT_DELETEDATE IS '댓글 삭제일';

-- 댓글-답글 테이블 생성.
CREATE TABLE CMTANSWER
(
	CMTANS_NO           VARCHAR2(30)   NOT NULL              -- <!-- 댓글-답글 번호 -->
	, CMT_NO            VARCHAR2(30)   NOT NULL              -- <!-- 댓글 번호 -->
	, BM_NO             VARCHAR2(30)   NOT NULL              -- <!-- 일반회원 번호(작성자) -->
	, CMTANS_CONTENT    VARCHAR2(4000) NOT NULL              -- <!-- 댓글-답글 내용 -->
	, CMTANS_DELETEYN   VARCHAR2(2) DEFAULT 'Y' NOT NULL     -- <!-- 댓글-답글 삭제여부 -->
	, CMTANS_INSERTDATE DATE        DEFAULT SYSDATE NOT NULL -- <!-- 댓글-답글 등록일 -->
	, CMTANS_UPDATEDATE DATE        DEFAULT SYSDATE NOT NULL -- <!-- 댓글-답글 수정일 -->
	, CMTANS_DELETEDATE DATE                                 -- <!-- 댓글-답글 삭제일 -->
	, CONSTRAINT CMTANSWER_PK PRIMARY KEY (CMTANS_NO)
	, CONSTRAINT CMTANSWER_FK1 FOREIGN KEY (CMT_NO) REFERENCES COMMENTS (CMT_NO)
	, CONSTRAINT CMTANSWER_FK2 FOREIGN KEY (BM_NO) REFERENCES BASICMEMBER (BM_NO)
);
COMMENT ON TABLE CMTANSWER IS '댓글-답글 테이블';
COMMENT ON COLUMN CMTANSWER.CMTANS_NO IS '댓글-답글 번호, 형식:CMTANS+YYYYMMDD+0001';
COMMENT ON COLUMN CMTANSWER.CMT_NO IS '댓글 번호';
COMMENT ON COLUMN CMTANSWER.BM_NO IS '일반회원 번호(작성자)';
COMMENT ON COLUMN CMTANSWER.CMTANS_CONTENT IS '댓글-답글 내용';
COMMENT ON COLUMN CMTANSWER.CMTANS_DELETEYN IS '댓글-답글 삭제여부';
COMMENT ON COLUMN CMTANSWER.CMTANS_INSERTDATE IS '댓글-답글 등록일';
COMMENT ON COLUMN CMTANSWER.CMTANS_UPDATEDATE IS '댓글-답글 수정일';
COMMENT ON COLUMN CMTANSWER.CMTANS_DELETEDATE IS '댓글-답글 삭제일';

-- 1:1문의 테이블 생성.
CREATE TABLE COMPLAIN
(
	CP_NO           VARCHAR2(30)   NOT NULL              -- <!-- 1:1문의 번호 -->
	, CP_TITLE      VARCHAR2(100)  NOT NULL              -- <!-- 1:1문의 제목 -->
	, BM_NO         VARCHAR2(30)   NOT NULL              -- <!-- 일반회원 번호(작성자) -->
	, CP_CONTENT    VARCHAR2(4000) NOT NULL              -- <!-- 1:1문의 내용 -->
	, CP_DELETEYN   VARCHAR2(2) DEFAULT 'Y' NOT NULL     -- <!-- 1:1문의 삭제여부 -->
	, CP_INSERTDATE DATE        DEFAULT SYSDATE NOT NULL -- <!-- 1:1문의 등록일 -->
	, CP_UPDATEDATE DATE        DEFAULT SYSDATE NOT NULL -- <!-- 1:1문의 수정일 -->
	, CP_DELETEDATE DATE                                 -- <!-- 1:1문의 삭제일 -->
	, CONSTRAINT COMPLAIN_PK PRIMARY KEY (CP_NO)
	, CONSTRAINT COMPLAIN_FK1 FOREIGN KEY (BM_NO) REFERENCES BASICMEMBER (BM_NO)
);
COMMENT ON TABLE COMPLAIN IS '1:1문의 테이블';
COMMENT ON COLUMN COMPLAIN.CP_NO IS '1:1문의 번호, 형식:CP+YYYYMMDD+0001';
COMMENT ON COLUMN COMPLAIN.CP_TITLE IS '1:1문의 제목';
COMMENT ON COLUMN COMPLAIN.BM_NO IS '일반회원 번호(작성자)';
COMMENT ON COLUMN COMPLAIN.CP_CONTENT IS '1:1문의 내용';
COMMENT ON COLUMN COMPLAIN.CP_DELETEYN IS '1:1문의 삭제여부';
COMMENT ON COLUMN COMPLAIN.CP_INSERTDATE IS '1:1문의 등록일';
COMMENT ON COLUMN COMPLAIN.CP_UPDATEDATE IS '1:1문의 수정일';
COMMENT ON COLUMN COMPLAIN.CP_DELETEDATE IS '1:1문의 삭제일';

-- 1:1문의-답변 테이블 생성.
CREATE TABLE CPANSWER
(
	CPANS_NO           VARCHAR2(30)   NOT NULL                 -- <!-- 1:1문의-답변 번호 -->
	, CP_NO            VARCHAR2(100)  NOT NULL                 -- <!-- 1:1문의 번호 -->
	, BM_NO            VARCHAR2(20)   NOT NULL                 -- <!-- 일반회원 번호(작성자) -->
	, CPANS_CONTENT    VARCHAR2(4000) NOT NULL                 -- <!-- 1:1문의-답변 내용 -->
	, CPANS_DELETEYN   VARCHAR2(2)    DEFAULT 'Y' NOT NULL     -- <!-- 1:1문의_답변 삭제여부 -->
	, CPANS_INSERTDATE DATE           DEFAULT SYSDATE NOT NULL -- <!-- 1:1문의_답변 등록일 -->
	, CPANS_UPDATEDATE DATE           DEFAULT SYSDATE NOT NULL -- <!-- 1:1문의_답변 수정일 -->
	, CPANS_DELETEDATE DATE                                    -- <!-- 1:1문의_답변 삭제일 -->
	, CONSTRAINT CPANSWER_PK PRIMARY KEY (CPANS_NO)
	, CONSTRAINT CPANSWER_FK1 FOREIGN KEY (CP_NO) REFERENCES COMPLAIN (CP_NO)
	, CONSTRAINT CPANSWER_FK2 FOREIGN KEY (BM_NO) REFERENCES BASICMEMBER (BM_NO)
);
COMMENT ON TABLE CPANSWER IS '1:1문의-답변 테이블';
COMMENT ON COLUMN CPANSWER.CPANS_NO IS '1:1문의-답변 번호, 형식:CPANS+YYYYMMDD+0001';
COMMENT ON COLUMN CPANSWER.CP_NO IS '1:1문의 번호';
COMMENT ON COLUMN CPANSWER.BM_NO IS '일반회원 번호(작성자)';
COMMENT ON COLUMN CPANSWER.CPANS_CONTENT IS '1:1문의-답변 내용';
COMMENT ON COLUMN CPANSWER.CPANS_DELETEYN IS '1:1문의_답변 삭제여부';
COMMENT ON COLUMN CPANSWER.CPANS_INSERTDATE IS '1:1문의_답변 등록일';
COMMENT ON COLUMN CPANSWER.CPANS_UPDATEDATE IS '1:1문의_답변 수정일';
COMMENT ON COLUMN CPANSWER.CPANS_DELETEDATE IS '1:1문의_답변 삭제일';

-- 신고 테이블 생성.
CREATE TABLE REPORT
(
	RP_NO           VARCHAR2(30)   NOT NULL       -- <!-- 신고 번호 -->
	, BM_NO         VARCHAR2(30)   NOT NULL       -- <!-- 일반회원 번호(신고자) -->
	, RP_BNO        VARCHAR2(30)   NOT NULL       -- <!-- 메인 게시글 번호(신고한 글) -->
	, RPANS_CONTENT VARCHAR2(4000) NOT NULL       -- <!-- 신고-답변 내용 -->
	, RP_INSERTDATE DATE DEFAULT SYSDATE NOT NULL -- <!-- 신고 등록일 -->
	, RP_REPLYDATE  DATE                          -- <!-- 신고 답변일 -->
	, CONSTRAINT REPORT_PK PRIMARY KEY (RP_NO)
	, CONSTRAINT REPORT_FK1 FOREIGN KEY (BM_NO) REFERENCES BASICMEMBER (BM_NO)
);
COMMENT ON TABLE REPORT IS '신고 테이블';
COMMENT ON COLUMN REPORT.RP_NO IS '신고 번호, 형식:RP+YYYYMMDD+0001';
COMMENT ON COLUMN REPORT.BM_NO IS '일반회원 번호(신고자)';
COMMENT ON COLUMN REPORT.RP_BNO IS '메인 게시글 번호(신고한 글)';
COMMENT ON COLUMN REPORT.RPANS_CONTENT IS '신고-답변 내용';
COMMENT ON COLUMN REPORT.RP_INSERTDATE IS '신고 등록일';
COMMENT ON COLUMN REPORT.RP_REPLYDATE IS '신고 답변일';

-- 신고-답변 테이블 생성.
CREATE TABLE RPANSWER
(
	RPANS_NO        VARCHAR2(30) NOT NULL -- <!-- 신고-답변 번호 -->
	, RPANS_TITLE   VARCHAR2(500)         -- <!-- 신고-답변 제목 -->
	, RPANS_CONTENT VARCHAR2(500)         -- <!-- 신고-답변 내용 -->
	, CONSTRAINT RPANSWER_PK PRIMARY KEY (RPANS_NO)
);
COMMENT ON TABLE RPANSWER IS '신고-답변 테이블';
COMMENT ON COLUMN RPANSWER.RPANS_NO IS '신고-답변 번호, 형식:RPANS+0001';
COMMENT ON COLUMN RPANSWER.RPANS_TITLE IS '신고-답변 제목';
COMMENT ON COLUMN RPANSWER.RPANS_CONTENT IS '신고-답변 내용';

-- 블랙리스트 테이블 생성.
CREATE TABLE BLACKLIST
(
	BL_NO            VARCHAR2(30) NOT NULL         -- <!-- 블랙리스트 번호 -->
	, BM_NO          VARCHAR2(30) NOT NULL         -- <!-- 일반회원 번호 -->
	, BM_ID          VARCHAR2(40) NOT NULL         -- <!-- 일반회원 아이디 -->
	, RPANS_CONTENT  VARCHAR2(30) NOT NULL         -- <!-- 블랙리스트 신고내용 -->
	, BL_INSERTDATE  DATE DEFAULT SYSDATE NOT NULL -- <!-- 블랙리스트 등록일 -->
	, BL_RELEASEDATE DATE                          -- <!-- 블랙리스트 해제일 -->
	, CONSTRAINT BLACKLIST_PK PRIMARY KEY (BL_NO)
	, CONSTRAINT BLACKLIST_FK1 FOREIGN KEY (BM_NO) REFERENCES BASICMEMBER (BM_NO)
);
COMMENT ON TABLE BLACKLIST IS '블랙리스트 테이블';
COMMENT ON COLUMN BLACKLIST.BL_NO IS '블랙리스트 번호, 형식:BL+YYYYMMDD+0001';
COMMENT ON COLUMN BLACKLIST.BM_NO IS '일반회원 번호';
COMMENT ON COLUMN BLACKLIST.BM_ID IS '일반회원 아이디';
COMMENT ON COLUMN BLACKLIST.RPANS_CONTENT IS '블랙리스트 신고내용';
COMMENT ON COLUMN BLACKLIST.BL_INSERTDATE IS '블랙리스트 등록일';
COMMENT ON COLUMN BLACKLIST.BL_RELEASEDATE IS '블랙리스트 해제일';